ALTER TABLE tblappointments
  ADD COLUMN IF NOT EXISTS notes TEXT NULL AFTER blood_bank;

ALTER TABLE tblappointments
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
